version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: backend_app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: casino_brand_toplist
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./backend/src/database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    container_name: frontend_app
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
